name: Send webhook to request review
on:
  pull_request:
    types: [review_requested]
jobs:
  review_requested:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook message
        uses: neonidian/teams-notify-build-status@v3
        with:
          webhookUrl:: ${{ secrets.WEBHOOK_URL }}
          title: >-
            [Repository link](${{ github.server_url }}/${{ github.repository }})
          message: Review to PR requested
