name: Send webhook to request review
on:
  pull_request:
    types: [review_requested]
jobs:
  review_requested:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook message
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_type: 'json-extended'
